namespace BurgerKioskWeek1;

partial class Form1
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        lblTitle = new Label();
        grpMenu = new GroupBox();
        picChicken = new PictureBox();
        picBulgogi = new PictureBox();
        picHam = new PictureBox();
        rdoChickenBurger = new RadioButton();
        rdoBulgogiBurger = new RadioButton();
        rdoHamBurger = new RadioButton();
        grpOption = new GroupBox();
        chkSauce = new CheckBox();
        chkCheese = new CheckBox();
        chkCola = new CheckBox();
        chkPotato = new CheckBox();
        grpOrder = new GroupBox();
        lstOrder = new ListBox();
        lblTotalTitle = new Label();
        lblTotalCost = new Label();
        btnOrder = new Button();
        btnReset = new Button();
        lblStatus = new Label();
        grpMenu.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)picChicken).BeginInit();
        ((System.ComponentModel.ISupportInitialize)picBulgogi).BeginInit();
        ((System.ComponentModel.ISupportInitialize)picHam).BeginInit();
        grpOption.SuspendLayout();
        grpOrder.SuspendLayout();
        SuspendLayout();
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("맑은 고딕", 18F, FontStyle.Bold, GraphicsUnit.Point, 129);
        lblTitle.ForeColor = Color.RoyalBlue;
        lblTitle.Location = new Point(20, 18);
        lblTitle.Name = "lblTitle";
        lblTitle.Size = new Size(206, 32);
        lblTitle.TabIndex = 0;
        lblTitle.Text = "버거 주문 키오스크";
        grpMenu.Controls.Add(picChicken);
        grpMenu.Controls.Add(picBulgogi);
        grpMenu.Controls.Add(picHam);
        grpMenu.Controls.Add(rdoChickenBurger);
        grpMenu.Controls.Add(rdoBulgogiBurger);
        grpMenu.Controls.Add(rdoHamBurger);
        grpMenu.Font = new Font("맑은 고딕", 10F, FontStyle.Bold, GraphicsUnit.Point, 129);
        grpMenu.ForeColor = Color.Firebrick;
        grpMenu.Location = new Point(20, 72);
        grpMenu.Name = "grpMenu";
        grpMenu.Size = new Size(238, 250);
        grpMenu.TabIndex = 1;
        grpMenu.TabStop = false;
        grpMenu.Text = "메뉴 선택";
        picChicken.BackColor = Color.MistyRose;
        picChicken.BorderStyle = BorderStyle.FixedSingle;
        picChicken.Location = new Point(127, 176);
        picChicken.Name = "picChicken";
        picChicken.Size = new Size(74, 46);
        picChicken.TabIndex = 5;
        picChicken.TabStop = false;
        picBulgogi.BackColor = Color.Bisque;
        picBulgogi.BorderStyle = BorderStyle.FixedSingle;
        picBulgogi.Location = new Point(127, 102);
        picBulgogi.Name = "picBulgogi";
        picBulgogi.Size = new Size(74, 46);
        picBulgogi.TabIndex = 4;
        picBulgogi.TabStop = false;
        picHam.BackColor = Color.PeachPuff;
        picHam.BorderStyle = BorderStyle.FixedSingle;
        picHam.Location = new Point(127, 29);
        picHam.Name = "picHam";
        picHam.Size = new Size(74, 46);
        picHam.TabIndex = 3;
        picHam.TabStop = false;
        rdoChickenBurger.AutoSize = true;
        rdoChickenBurger.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        rdoChickenBurger.ForeColor = Color.Black;
        rdoChickenBurger.Location = new Point(17, 190);
        rdoChickenBurger.Name = "rdoChickenBurger";
        rdoChickenBurger.Size = new Size(109, 23);
        rdoChickenBurger.TabIndex = 2;
        rdoChickenBurger.TabStop = true;
        rdoChickenBurger.Text = "치킨버거 3000";
        rdoChickenBurger.UseVisualStyleBackColor = true;
        rdoBulgogiBurger.AutoSize = true;
        rdoBulgogiBurger.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        rdoBulgogiBurger.ForeColor = Color.Black;
        rdoBulgogiBurger.Location = new Point(17, 116);
        rdoBulgogiBurger.Name = "rdoBulgogiBurger";
        rdoBulgogiBurger.Size = new Size(120, 23);
        rdoBulgogiBurger.TabIndex = 1;
        rdoBulgogiBurger.TabStop = true;
        rdoBulgogiBurger.Text = "불고기버거 4000";
        rdoBulgogiBurger.UseVisualStyleBackColor = true;
        rdoHamBurger.AutoSize = true;
        rdoHamBurger.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        rdoHamBurger.ForeColor = Color.Black;
        rdoHamBurger.Location = new Point(17, 43);
        rdoHamBurger.Name = "rdoHamBurger";
        rdoHamBurger.Size = new Size(98, 23);
        rdoHamBurger.TabIndex = 0;
        rdoHamBurger.TabStop = true;
        rdoHamBurger.Text = "햄버거 5000";
        rdoHamBurger.UseVisualStyleBackColor = true;
        grpOption.Controls.Add(chkSauce);
        grpOption.Controls.Add(chkCheese);
        grpOption.Controls.Add(chkCola);
        grpOption.Controls.Add(chkPotato);
        grpOption.Font = new Font("맑은 고딕", 10F, FontStyle.Bold, GraphicsUnit.Point, 129);
        grpOption.ForeColor = Color.Firebrick;
        grpOption.Location = new Point(274, 72);
        grpOption.Name = "grpOption";
        grpOption.Size = new Size(171, 180);
        grpOption.TabIndex = 2;
        grpOption.TabStop = false;
        grpOption.Text = "추가 옵션";
        chkSauce.AutoSize = true;
        chkSauce.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        chkSauce.ForeColor = Color.Black;
        chkSauce.Location = new Point(16, 137);
        chkSauce.Name = "chkSauce";
        chkSauce.Size = new Size(93, 23);
        chkSauce.TabIndex = 3;
        chkSauce.Text = "소스 추가 500";
        chkSauce.UseVisualStyleBackColor = true;
        chkCheese.AutoSize = true;
        chkCheese.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        chkCheese.ForeColor = Color.Black;
        chkCheese.Location = new Point(16, 102);
        chkCheese.Name = "chkCheese";
        chkCheese.Size = new Size(108, 23);
        chkCheese.TabIndex = 2;
        chkCheese.Text = "치즈 추가 1500";
        chkCheese.UseVisualStyleBackColor = true;
        chkCola.AutoSize = true;
        chkCola.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        chkCola.ForeColor = Color.Black;
        chkCola.Location = new Point(16, 67);
        chkCola.Name = "chkCola";
        chkCola.Size = new Size(85, 23);
        chkCola.TabIndex = 1;
        chkCola.Text = "콜라 2500";
        chkCola.UseVisualStyleBackColor = true;
        chkPotato.AutoSize = true;
        chkPotato.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        chkPotato.ForeColor = Color.Black;
        chkPotato.Location = new Point(16, 32);
        chkPotato.Name = "chkPotato";
        chkPotato.Size = new Size(100, 23);
        chkPotato.TabIndex = 0;
        chkPotato.Text = "감자튀김 3500";
        chkPotato.UseVisualStyleBackColor = true;
        grpOrder.Controls.Add(lstOrder);
        grpOrder.Font = new Font("맑은 고딕", 10F, FontStyle.Bold, GraphicsUnit.Point, 129);
        grpOrder.ForeColor = Color.Firebrick;
        grpOrder.Location = new Point(463, 72);
        grpOrder.Name = "grpOrder";
        grpOrder.Size = new Size(214, 250);
        grpOrder.TabIndex = 3;
        grpOrder.TabStop = false;
        grpOrder.Text = "주문 내역";
        lstOrder.Font = new Font("맑은 고딕", 10F, FontStyle.Regular, GraphicsUnit.Point, 129);
        lstOrder.FormattingEnabled = true;
        lstOrder.ItemHeight = 19;
        lstOrder.Location = new Point(16, 30);
        lstOrder.Name = "lstOrder";
        lstOrder.Size = new Size(180, 194);
        lstOrder.TabIndex = 0;
        lblTotalTitle.AutoSize = true;
        lblTotalTitle.Font = new Font("맑은 고딕", 12F, FontStyle.Bold, GraphicsUnit.Point, 129);
        lblTotalTitle.ForeColor = Color.RoyalBlue;
        lblTotalTitle.Location = new Point(459, 335);
        lblTotalTitle.Name = "lblTotalTitle";
        lblTotalTitle.Size = new Size(81, 21);
        lblTotalTitle.TabIndex = 4;
        lblTotalTitle.Text = "총 금액 :";
        lblTotalCost.AutoSize = true;
        lblTotalCost.Font = new Font("맑은 고딕", 12F, FontStyle.Bold, GraphicsUnit.Point, 129);
        lblTotalCost.ForeColor = Color.RoyalBlue;
        lblTotalCost.Location = new Point(537, 335);
        lblTotalCost.Name = "lblTotalCost";
        lblTotalCost.Size = new Size(45, 21);
        lblTotalCost.TabIndex = 5;
        lblTotalCost.Text = "0원";
        btnOrder.BackColor = Color.LimeGreen;
        btnOrder.FlatStyle = FlatStyle.Flat;
        btnOrder.Font = new Font("맑은 고딕", 11F, FontStyle.Bold, GraphicsUnit.Point, 129);
        btnOrder.ForeColor = Color.White;
        btnOrder.Location = new Point(463, 372);
        btnOrder.Name = "btnOrder";
        btnOrder.Size = new Size(96, 42);
        btnOrder.TabIndex = 6;
        btnOrder.Text = "주문하기";
        btnOrder.UseVisualStyleBackColor = false;
        btnReset.BackColor = Color.Red;
        btnReset.FlatStyle = FlatStyle.Flat;
        btnReset.Font = new Font("맑은 고딕", 11F, FontStyle.Bold, GraphicsUnit.Point, 129);
        btnReset.ForeColor = Color.White;
        btnReset.Location = new Point(581, 372);
        btnReset.Name = "btnReset";
        btnReset.Size = new Size(96, 42);
        btnReset.TabIndex = 7;
        btnReset.Text = "초기화";
        btnReset.UseVisualStyleBackColor = false;
        lblStatus.Font = new Font("맑은 고딕", 10F, FontStyle.Bold, GraphicsUnit.Point, 129);
        lblStatus.ForeColor = Color.Crimson;
        lblStatus.Location = new Point(20, 334);
        lblStatus.Name = "lblStatus";
        lblStatus.Size = new Size(425, 50);
        lblStatus.TabIndex = 8;
        lblStatus.TextAlign = ContentAlignment.MiddleLeft;
        AcceptButton = btnOrder;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(700, 435);
        Controls.Add(lblStatus);
        Controls.Add(btnReset);
        Controls.Add(btnOrder);
        Controls.Add(lblTotalCost);
        Controls.Add(lblTotalTitle);
        Controls.Add(grpOrder);
        Controls.Add(grpOption);
        Controls.Add(grpMenu);
        Controls.Add(lblTitle);
        FormBorderStyle = FormBorderStyle.FixedSingle;
        MaximizeBox = false;
        Name = "Form1";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Burger Kiosk";
        grpMenu.ResumeLayout(false);
        grpMenu.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)picChicken).EndInit();
        ((System.ComponentModel.ISupportInitialize)picBulgogi).EndInit();
        ((System.ComponentModel.ISupportInitialize)picHam).EndInit();
        grpOption.ResumeLayout(false);
        grpOption.PerformLayout();
        grpOrder.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion

    private Label lblTitle;
    private GroupBox grpMenu;
    private PictureBox picChicken;
    private PictureBox picBulgogi;
    private PictureBox picHam;
    private RadioButton rdoChickenBurger;
    private RadioButton rdoBulgogiBurger;
    private RadioButton rdoHamBurger;
    private GroupBox grpOption;
    private CheckBox chkSauce;
    private CheckBox chkCheese;
    private CheckBox chkCola;
    private CheckBox chkPotato;
    private GroupBox grpOrder;
    private ListBox lstOrder;
    private Label lblTotalTitle;
    private Label lblTotalCost;
    private Button btnOrder;
    private Button btnReset;
    private Label lblStatus;
}
